allow-spawners: false # Should entities spawned by spawners count towards a task?
save-timer: 120 # In seconds, how often should player data be saved to disk?


tasks:
   0: # Id, this doesn't do anything but must be unique
      mob-type: ZOMBIE # List of mob types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
      kills: 13 # Required kills for the task
      name: Zombie Subjugation
      description: # Note that longer lines may be cut off for players with smaller monitors / larger gui sizes
       - "&7The local zombie population"
       - "&7is getting out of control."
       - "&7Please bring the population"
       - "&7down to manageable levels."
      reward: 11 # Points to reward
   1:
      mob-type: ENDERMAN
      kills: 1
      name: Enderman Assassination
      description:
       - "&7You will be paid"
       - "&7to end the life"
       - "&7of an enderman."
      reward: 7
   2:
      mob-type: GUARDIAN
      kills: 13
      name: Unwanted Security
      description:
      - "&7There is some, uh,"
      - "&7let's say guardians"
      - "&7of a &9sea temple&7."
      - "&7We don't want them there."
      reward: 11
   3:
      mob-type: PIGLIN
      kills: 16
      name: Pork BBQ
      description:
      - "&7What can I say?"
      - "&7I like &dpork&7..."
      - "&7Nothing to do with"
      - "&7their &6gold&7, I swear!"
      reward: 15
   4:
      mob-type: CREEPER
      kills: 5
      name: Griefed House
      description:
       - "&7MY HOUSE!!!"
      reward: 12
   5:
      mob-type: SKELETON
      kills: 7
      name: Dog Treat
      description:
       - "&7I'd like to treat"
       - "&7my dog to something."
      reward: 8
   6:
      mob-type: PUFFERFISH
      kills: 4
      name: Seafood Delivery
      description:
       - "&bBart's Seafoods &7would"
       - "&7like to order a shipment"
       - "&7of fresh &bseafood&7."
      reward: 18
   7:
     mob-type: SKELETON
     kills: 17
     name: Skeleton Subjugation
     description:
       - "&7The local skeleton population"
       - "&7is getting out of control."
       - "&7Please bring the population"
       - "&7down to manageable levels."
     reward: 13
   8:
     mob-type: SPIDER
     kills: 20
     name: Spider Subjugation
     description:
       - "&7The local spider population"
       - "&7is getting out of control."
       - "&7Please bring the population"
       - "&7down to manageable levels."
     reward: 18
   9:
    mob-type: SPIDER
    kills: 3
    name: "Eeek! Spiders!"
    description:
     - "&7I hate spiders... &c:("
    reward: 6


shop:
   # These are sorted by id, items with a lower id will appear closer to the first page of the shop
   0: # Id, this must be unique
      name: "Permanent Flight"
      description: # Note that longer lines may be cut off for players with smaller monitors / larger gui sizes
       - "&7Gain access to"
       - "&7the /fly command."
      cost: 150 # Cost in slayer points
      commands: # These commands will be executed when a player purchases the item. %player% will be replaced with the players username.
      # These commands will be executed by the console.
       - "lp user/group %player% permission set essentials.fly true"
      material: FEATHER # Item type to display this as. List of item types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
      itemAmount: 1 # Amount to show in menu, this is purely visual.
      purchases: 1 # Amount of times a player can purchase this. -1 is infinite
   1:
      name: "Diamond Block"
      description:
       - "&7A solid cube of &bDiamond"
      cost: 18
      commands:
       - "give %player% diamond_block 1"
      material: DIAMOND_BLOCK
      itemAmount: 1
      purchases: -1
   2:
      name: "1395 Experience Points"
      description:
       - "&7Enchant forever!"
       - "&8At level 0, 30 levels will be gained"
      cost: 10
      commands:
       - "xp add %player% 1395"
      material: LIME_WOOL
      itemAmount: 1
      purchases: -1