# Support: https://discord.gg/4BUuKYWY6v

allow-spawners: false # Should entities spawned by spawners count towards a task?
save-timer: 120 # In seconds, how often should player data be saved to disk?
action-bar-enabled: false # Customise message in lang.yml
claim-reward-opens-main-menu: false
back-buttons:
  shop: 'slayer %player% -s' # A back button will be placed in the shop gui that opens the slayer menu by running the command as console
  monsters: 'slayer %player% -s' # Monsters slain GUI
  reward: 'none' # Claim reward GUI
  main: 'none' # No back button will be placed in the main slayer gui

# ALL IDS MUST BE NUMBERS
tasks:
   0: # Id, this doesn't do anything but must be unique
      mob-type: 0 # Id of a mob-type, as defined in mob-types.yml
      kills: 13 # Required kills for the task
      name: Zombie Subjugation
      description:
       - "&7The local zombie population"
       - "&7is getting out of control."
       - "&7Please bring the population"
       - "&7down to manageable levels."
      reward: 11 # Points to reward
   1:
      mob-type: 1
      kills: 1
      name: Enderman Assassination
      description:
       - "&7You will be paid"
       - "&7to end the life"
       - "&7of an enderman."
      reward: 7
   2:
      mob-type: 2
      kills: 13
      name: Unwanted Security
      description:
      - "&7There is some, uh,"
      - "&7let's say guardians"
      - "&7of a &9sea temple&7."
      - "&7We don't want them there."
      reward: 11
   3:
      mob-type: 3
      kills: 16
      name: Pork BBQ
      description:
      - "&7What can I say?"
      - "&7I like &dpork&7..."
      - "&7Nothing to do with"
      - "&7their &6gold&7, I swear!"
      reward: 15
   4:
      mob-type: 4
      kills: 5
      name: Griefed House
      description:
       - "&7MY HOUSE!!!"
      reward: 12
   5:
      mob-type: 5
      kills: 7
      name: Dog Treat
      description:
       - "&7I'd like to treat"
       - "&7my dog to something."
      reward: 8
   6:
      mob-type: 6
      kills: 4
      name: Seafood Delivery
      description:
       - "&bBart's Seafoods &7would"
       - "&7like to order a shipment"
       - "&7of fresh &bseafood&7."
      reward: 18
   7:
      mob-type: 5
      kills: 17
      name: Skeleton Subjugation
      description:
       - "&7The local skeleton population"
       - "&7is getting out of control."
       - "&7Please bring the population"
       - "&7down to manageable levels."
      reward: 13
   8:
      mob-type: 7
      kills: 20
      name: Spider Subjugation
      description:
       - "&7The local spider population"
       - "&7is getting out of control."
       - "&7Please bring the population"
       - "&7down to manageable levels."
      reward: 18
   9:
      mob-type: 7
      kills: 3
      name: "Eeek! Spiders!"
      description:
       - "&7I hate spiders... &c:("
      reward: 6
   10:
      mob-type: 8
      kills: 1
      name: "&6&lSuper Steak"
      description:
       - "&7Dave wants a &6&lsuper steak&7!"
      reward: 1
   11: # If you have Mythic Mobs you could make this an actual Skeletal Knight!
      mob-type: 5
      kills: 1
      name: Skeletal Knight Subjugation
      description:
       - "&7A Skeletal Knight has been"
       - "&7sighted. Your task is to slay it."
      reward: 18

# The default shop uses commands from LuckPerms and Essentials, however you can use purely vanilla commands, or commands in other plugins.
shop:
   # These are sorted by id, items with a lower id will appear closer to the first page of the shop
   0: # Id, this must be unique
      name: "Permanent Flight"
      description:
       - "&7Gain access to"
       - "&7the /fly command."
      cost: 150 # Cost in slayer points
      commands: # These commands will be executed when a player purchases the item. %player% will be replaced with the players username.
      # These commands will be executed by the console.
       - "lp user %player% permission set essentials.fly true"
      material: FEATHER # Item type to display this as. List of item types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
      itemAmount: 1 # Amount to show in menu, this is purely visual.
      purchases: 1 # Amount of times a player can purchase this. -1 is infinite
   1:
      name: "Diamond Block"
      description:
       - "&7A solid cube of &bDiamond"
      cost: 18
      commands:
       - "give %player% diamond_block 1"
      material: DIAMOND_BLOCK
      itemAmount: 1
      purchases: -1
   2:
      name: "1395 Experience Points"
      description:
       - "&7Enchant forever!"
       - "&8At level 0, 30 levels will be gained"
      cost: 10
      commands:
       - "minecraft:xp add %player% 1395"
      material: LIME_WOOL
      itemAmount: 1
      purchases: -1
   3:
      name: "$10,000"
      description:
       - "&bCold hard cash. Limited stock."
      cost: 14
      commands:
       - "eco give %player% 10000"
      material: PAPER
      itemAmount: 1
      purchases: 5