main: me.unfear.Slayer.Main
name: Slayer
author: unfear
api-version: 1.13
description: Receive slayer tasks from the Slayer Master
version: 0.5.0
softdepend: [ MythicMobs, PlaceholderAPI ]
commands:
  slayer:
    description: Open the slayer menu
    permission: slayer.open
    aliases: [ slayermaster, slayermenu, slayertask ]
  canceltask:
    description: Cancel a players task!
    permission: slayer.canceltask
    aliases: [ cancelslayertask, slayercancel ]
  collectrewards:
    description: Collect rewards remotely
    permission: slayer.collectreward
    aliases: [ slayercollectreward, slayerclaimreward, collectreward ]
  slayerbuy:
    description: Buy items remotely
    permission: slayer.buy
    aliases: [ slayerpurchase, slayershopbuy ]
  starttask:
    description: Start a slayer task
    permission: slayer.startask
    aliases: [ slayerreceivetask ]
  reloadslayer:
    description: Reload Slayer configs
    permission: slayer.reload
    aliases: [ slayerreload ]