allow-spawners: false # Should entities spawned by spawners count towards a task?
save-timer: 120 # In seconds, how often should player data be saved to disk?


tasks:
   0: # Id, this doesn't do anything but must be unique
      mob-type: ZOMBIE # List of mob types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
      kills: 13 # Required kills for the task
      name: Zombie Subjugation
      description: # Note that longer lines may be cut off for players with smaller monitors / larger gui sizes
       - "&7The local zombie population"
       - "&7is getting out of control."
       - "&7Please bring the population"
       - "&7down to manageable levels."
      reward: 11 # Points to reward
   1:
      mob-type: ENDERMAN
      kills: 1
      name: Enderman Assassination
      description:
       - "&7You will be paid"
       - "&7to end the life"
       - "&7of an enderman."
      reward: 7


shop:
   # These are sorted by id, items with a lower id will appear closer to the first page of the shop
   0: # Id, this must be unique
      name: "Permanent Flight"
      description: # Note that longer lines may be cut off for players with smaller monitors / larger gui sizes
       - "&7Gain access to"
       - "&7the /fly command."
      cost: 15 # Cost in slayer points
      commands: # These commands will be executed when a player purchases the item. %player% will be replaced with the players username.
      # These commands will be executed by the console.
       - "lp user/group %player% permission set essentials.fly true"
      material: FEATHER # Item type to display this as. List of item types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
      itemAmount: 1 # Amount to show in menu, this is purely visual.
      purchases: 1 # Amount of times a player can purchase this. -1 is infinite
   1:
      name: "Diamond Block"
      description:
       - "&7A solid cube of &bDiamond"
      cost: 2
      commands:
       - "give %player% diamond_block 1"
      material: DIAMOND_BLOCK
      itemAmount: 1
      purchases: -1