main: me.unfear.Slayer.Slayer
name: Slayer
author: unfear
api-version: 1.13
description: Receive slayer tasks from the Slayer Master
version: 1.0
commands:
   slayer:
      description: Open the slayer menu
      permission: slayer.open
      aliases: [slayermaster, slayermenu, slayertask]